#!/bin/sh
# MyKAI Node — one-line installer for Docker hosts (NAS, VPS, home server).
#
# Usage:
#   bash <(curl -fsSL https://mykai.dev/install.sh)
#
# Or with a specific account key (unify stats with an existing desktop install):
#   MYKAI_ACCOUNT_KEY=acc_<32hex> bash <(curl -fsSL https://mykai.dev/install.sh)
#
# What this script does:
#   1. Verifies docker + docker compose are installed
#   2. Creates ~/.mykai-node/ with a docker-compose.yml describing two services:
#        kaspad           — kaspanet/rusty-kaspa:latest (the actual Kaspa node)
#        mykai-monitor    — kasmap/mykai-headless:latest (MyKAI's telemetry monitor)
#   3. Brings the stack up with `docker compose up -d`
#   4. Prints the final account key + container status
#
# Idempotent: safe to re-run. Re-running upgrades both images to :latest and
# restarts the stack. The persisted accountKey + chain data survive the upgrade
# (both stored in named docker volumes).
#
# Uninstall:
#   cd ~/.mykai-node && docker compose down -v   # removes containers + data
#   rm -rf ~/.mykai-node

set -eu

INSTALL_DIR="${MYKAI_INSTALL_DIR:-$HOME/.mykai-node}"
NODE_NAME="${MYKAI_NODE_NAME:-MyKAI Cloud Node}"
ACCOUNT_KEY="${MYKAI_ACCOUNT_KEY:-}"

say() { printf '\033[1;36m[MyKAI]\033[0m %s\n' "$1"; }
fail() { printf '\033[1;31m[MyKAI] %s\033[0m\n' "$1" >&2; exit 1; }

# ─── Prerequisite checks ────────────────────────────────────────────────────

say "MyKAI Node installer"

if ! command -v docker >/dev/null 2>&1; then
  fail "docker is not installed. Install Docker first:
       https://docs.docker.com/engine/install/   (Linux)
       https://docs.docker.com/desktop/install/  (Mac, Windows)
       Or use your NAS's App Central (Asustor / Synology have 1-click Docker)."
fi

# Compose can be docker-compose (legacy) or `docker compose` (plugin).
COMPOSE=""
if docker compose version >/dev/null 2>&1; then
  COMPOSE="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE="docker-compose"
else
  fail "docker compose is not installed. On Linux: apt install docker-compose-plugin
       On Mac/Windows: comes with Docker Desktop, so check your install."
fi
say "Docker found: $(docker --version | head -1)"
say "Compose found: $COMPOSE"

# ─── Generate or reuse accountKey ───────────────────────────────────────────

if [ -z "$ACCOUNT_KEY" ]; then
  # Try to reuse a previously-installed key.
  if [ -f "$INSTALL_DIR/.mykai-account-key" ]; then
    ACCOUNT_KEY=$(cat "$INSTALL_DIR/.mykai-account-key" 2>/dev/null || true)
    say "Reusing existing account key: ${ACCOUNT_KEY%????????????????????????}…"
  fi
fi

if [ -z "$ACCOUNT_KEY" ]; then
  # Auto-mint a fresh one. Format matches desktop's electron-store output:
  # acc_<32 hex chars>.
  if command -v openssl >/dev/null 2>&1; then
    HEX=$(openssl rand -hex 16)
  elif [ -r /dev/urandom ]; then
    HEX=$(od -An -N16 -tx1 /dev/urandom | tr -d ' \n')
  else
    fail "Can't generate a random key — no openssl, no /dev/urandom. Set
         MYKAI_ACCOUNT_KEY=acc_<32hex> manually and re-run."
  fi
  ACCOUNT_KEY="acc_${HEX}"
  say "Generated new account key: ${ACCOUNT_KEY%????????????????????????}…"
  say "To unify with a desktop MyKAI install later, set MYKAI_ACCOUNT_KEY"
  say "to your desktop's key and re-run this script."
fi

# Validate format defensively.
if ! printf '%s' "$ACCOUNT_KEY" | grep -Eq '^acc_[0-9a-f]{32}$'; then
  fail "MYKAI_ACCOUNT_KEY format is invalid. Expected: acc_<32 hex chars>.
       Got: $ACCOUNT_KEY"
fi

# ─── Write docker-compose.yml ───────────────────────────────────────────────

mkdir -p "$INSTALL_DIR"
echo "$ACCOUNT_KEY" > "$INSTALL_DIR/.mykai-account-key"
chmod 600 "$INSTALL_DIR/.mykai-account-key"

cat > "$INSTALL_DIR/docker-compose.yml" <<COMPOSE_EOF
# MyKAI Node — generated by https://mykai.dev/install.sh
# Edit MYKAI_NODE_NAME below if you want a custom label.
# To reset everything: docker compose down -v && rm -rf $INSTALL_DIR

services:
  kaspad:
    image: kaspanet/rusty-kaspa:latest
    container_name: mykai-kaspad
    restart: unless-stopped
    ports:
      - "16111:16111"     # P2P inbound. Forward this in your router too.
    volumes:
      - kaspad-data:/app/data
    command:
      - kaspad
      - --utxoindex
      - --listen=0.0.0.0:16111
      - --rpclisten-borsh=0.0.0.0:17110
      - --rpclisten-json=0.0.0.0:18110
      # Outbound peer count — matches MyKAI Node desktop default for
      # network-citizenship consistency.
      #
      # Desktop architecture (FYI for context): MyKAI's desktop build
      # randomly picks 3-or-4 curated Kaspa ecosystem seed peers from 5
      # different operators per launch (operator load spreading + fleet
      # topology randomization). The docker-compose path here doesn't
      # auto-add them via --addpeer — instead, kaspad uses its built-in
      # DNS seeders for bootstrap and gossip discovery for the rest.
      # Setting outpeers=14 matches the desktop total budget for
      # consistent network-load profile across the MyKAI fleet.
      #
      # NAS / VPS operators who want more (mining, observatory) can edit
      # this line in ~/.mykai-node/docker-compose.yml and run
      # `docker compose up -d` to apply.
      - --outpeers=9

  mykai-monitor:
    image: kasmap/mykai-headless:latest
    container_name: mykai-monitor
    restart: unless-stopped
    depends_on:
      - kaspad
    environment:
      - MYKAI_KASPAD_HOST=kaspad
      - MYKAI_BORSH_PORT=17110
      - MYKAI_JSON_PORT=18110
      - MYKAI_NETWORK=mainnet
      - MYKAI_IS_PUBLIC=true
      - MYKAI_NODE_NAME=${NODE_NAME}
      - MYKAI_ACCOUNT_KEY=${ACCOUNT_KEY}
    volumes:
      - mykai-data:/app/data

volumes:
  kaspad-data:
  mykai-data:
COMPOSE_EOF

say "Wrote $INSTALL_DIR/docker-compose.yml"

# ─── Pull + start ───────────────────────────────────────────────────────────

cd "$INSTALL_DIR"

say "Pulling latest images (this may take a few minutes on first run)…"
$COMPOSE pull

say "Starting containers…"
$COMPOSE up -d

# ─── Output ─────────────────────────────────────────────────────────────────

sleep 2
say ""
say "✓ MyKAI Node is running."
say ""
say "Account key:  $ACCOUNT_KEY"
say "Node name:    $NODE_NAME"
say "Install dir:  $INSTALL_DIR"
say ""
say "Container status:"
$COMPOSE ps
say ""
say "Next steps:"
say "  • Forward TCP port 16111 in your router to make this node reachable"
say "  • View logs:           cd $INSTALL_DIR && $COMPOSE logs -f mykai-monitor"
say "  • Stop everything:     cd $INSTALL_DIR && $COMPOSE down"
say "  • Stop + wipe data:    cd $INSTALL_DIR && $COMPOSE down -v"
say ""
say "Your node will show up at https://mykai.dev under \"My Nodes\""
say "within a few minutes (first heartbeat fires at ~15min cadence)."
